title: Victoria's Personal Website
description: Download resume, professoinal pic, etc.
theme: just-the-docs

url: https://jedi-force.github.io/website/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
